In [2]:
import torch # 如果pytorch安装成功即可导入
import numpy as np
print(torch.cuda.is_available()) # 查看CUDA是否可用
print(torch.cuda.device_count()) # 查看可用的CUDA数量
print(torch.version.cuda) # 查看CUDA的版本号


True
1
11.8


In [3]:
t1 = torch.Tensor([1, 2, 3])
print(t1)

tensor([1., 2., 3.])


In [8]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a1)
a = torch.tensor(a1)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)


In [9]:
# a1 = np.array([[1, 2, 3], [4, 5, 6]])
print(torch.ones(3,4))
print(a.size())
a.dim()

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 3])


2

In [10]:
a.transpose(0,1)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]], dtype=torch.int32)

In [16]:
a = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(a)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [19]:
y = torch.randn(2,3,4)
y

tensor([[[ 0.6645, -1.8586, -0.3585, -1.1817],
         [-0.7160, -1.7921, -0.7276,  0.8883],
         [ 0.3747,  0.9929, -0.2360, -0.7406]],

        [[-0.7568,  0.1126,  1.3787, -0.4011],
         [-1.4097, -1.8198, -0.2074,  1.1705],
         [-0.9309, -0.8842,  0.8036, -1.2736]]])

In [21]:
y.permute(1,0,2)

tensor([[[ 0.6645, -1.8586, -0.3585, -1.1817],
         [-0.7568,  0.1126,  1.3787, -0.4011]],

        [[-0.7160, -1.7921, -0.7276,  0.8883],
         [-1.4097, -1.8198, -0.2074,  1.1705]],

        [[ 0.3747,  0.9929, -0.2360, -0.7406],
         [-0.9309, -0.8842,  0.8036, -1.2736]]])

In [25]:
x = torch.tensor([1],dtype=torch.int32)
x

tensor([1], dtype=torch.int32)

In [26]:
torch.cuda.is_available()

True